config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users
  resources :pickups

  get '/login'     => 'sessions#new', as: :login
  post '/login'    => 'sessions#create', as: :create_login
  delete '/logout' => 'sessions#destroy', as: :logout
  match 'pickups/complete' => 'pickups#complete', :via => :post

end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pickups, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController

before_action :admin, only: [:index]

  def index
    @pickups = Pickup.all
    @pending_pickups = Pickup.where(completed: false)
    @completed_pickups = Pickup.where(completed: true)
  end

  def create
    # pickup_parameters[:date] = Date.strptime(pickup_parameters[:date],
    #                                             '%m/%d/%Y')
    @pickup = current_user.pickups.build(pickup_parameters)
     if @pickup.save
       redirect_to user_path(current_user)
     else 
       render :new
     end    
   end

  def edit
    @pickup = Pickup.find(params[:id])   
   end

   def update
    @pickup = Pickup.find(params[:id])

     if @pickup.update_attributes(pickup_parameters)
       redirect_to users_path
     else
       render "edit"
     end
   end

   def complete
     params[:pickups_check_box].each do |check|
       pickup_id = check
     t = Pickup.find_by_id(pickup_id)
         t.update_attribute(:completed, true)
     end
    redirect_to :action => 'index'

   end  


  private
  def pickup_parameters
    params.require(:pickup).permit(:address, :bins, :material, :date)
  end
 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.where(email: params[:login][:email]).first
    if user && user.authenticate(params[:login][:password])
      log_in(user)
      if user.admin == true
        redirect_to pickups_path(user)
      else
       redirect_to user_path(user)
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @pickup = Pickup.new 
  end

  def create
    @user = User.create(user_parameters)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path(@user)
    else 
      render :new
    end     
  end

  def edit
    @user = User.find(params[:id])   
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_parameters)
      redirect_to users_path
    else
      render "edit"
    end
  end

  def destroy
    @user =  User.find(params[:id]) 
    @user.destroy
    redirect_to login_path  
  end

  private
  def user_parameters
    params.require(:user).permit(:first_name, :last_name, :email, :street, :unit_number, :city, :state, :zip_code, :phone, :debit_card_number, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
      @user = User.new 
      i = rand(0..@@compliments.length)
      @compliment = @@compliments[i]
    end

    def method_name
      
    end

    @@compliments = [
    "A used aluminum can is recycled and back on the grocery shelf as a new can, in as little as 60 days. That's closed loop recycling at its finest!",
    "Recycling one aluminum can saves enough energy to run a TV for three hours -- or the equivalent of a half a gallon of gasoline.",
    "More aluminum goes into beverage cans than any other product.",
    "We use over 80,000,000,000 aluminum soda cans every year.",
    "A 60-watt light bulb can be run for over a day on the amount of energy saved by recycling 1 pound of steel. In one year in the United States, the recycling of steel saves enough energy to heat and light 18,000,000 homes!",
    "If every American recycled just one-tenth of their newspapers, we would save about 25,000,000 trees a year.",
    "Approximately 1 billion trees worth of paper are thrown away every year in the U.S.",
    "Plastic bags and other plastic garbage thrown into the ocean kill as many as 1,000,000 sea creatures every year!",
    "The 17 trees saved (above) can absorb a total of 250 pounds of carbon dioxide from the air each year. Burning that same ton of paper would create 1500 pounds of carbon dioxide.",
    "Every month, we throw out enough glass bottles and jars to fill up a giant skyscraper. All of these jars are recyclable!",
    "The U.S. is the #1 trash-producing country in the world at 1,609 pounds per person per year. This means that 5% of the world's people generate 40% of the world's waste.",
    "On average, it costs $30 per ton to recycle trash, $50 to send it to the landfill, and $65 to $75 to incinerate it.",
    "Motor oil never wears out, it just gets dirty. Oil can be recycled, re-refined and used again, reducing our reliance on imported oil.",
    "An estimated 80,000,000 Hershey's Kisses are wrapped each day, using enough aluminum foil to cover over 50 acres of space -- that's almost 40 football fields. All that foil is recyclable, but not many people realize it.",
    "Mining and transporting raw materials for glass produces about 385 pounds of waste for every ton of glass that is made. If recycled glass is substituted for half of the raw materials, the waste is cut by more than 80%.",
    "If you had a 15-year-old tree and made it into paper grocery bags, you'd get about 700 of them. A busy supermarket could use all of them in under an hour! This means in one year, one supermarket can go through over 6 million paper bags! Imagine how many supermarkets there are just in the United States!!!"
  ]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def admin
    if !current_user.admin
      redirect_to user_path(current_user)
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end

  def logged_in?
      !current_user.nil?
  end

  def log_out    
      session.delete(:user_id)
      @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trash4</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pickups/index.html.erb
<%= render "shared/menu" %>
<div id="admin-show">

	<div class="container" id="pending">
	
	<div>pending pickups</div>
	<%= form_tag("/pickups/complete/", :method => "post") do %>

		<ul>
			<% @pending_pickups.each do |pickup| %>
				<li><%= pickup.id %> <%= pickup.date %> <%= check_box_tag "pickups_check_box[]",pickup.id %> </li>
			<% end %>
		</ul>
		<%= submit_tag("Complete Pickups", :class=>"btn btn-success") %>
		<% end %>
	</div>

	<div class="container" id="completed">
	
	<div>completed pickups</div>
		<ul>
			<% @completed_pickups.each do |pickup| %>
				<li><%= pickup.id %></li>
			<% end %>
		</ul>

	</div>

</div>

app/views/shared/_login.html.erb
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <h3>Login</h3>

		<%= form_for :login, :url => create_login_path do |f| %>

			<div>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>


			<div>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>

			<div>
				<%= f.submit "Sign In!" %>
			</div>

		<% end %>
    </div>
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "TrVshio", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Account", user_path(current_user) %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>

        <% end %>
        <% if logged_in? == false %>

          <li><a class="btn" data-toggle="modal" data-target=".bs-example-modal-sm">Login</a></li>
          <li><a class="btn" data-toggle="modal" data-target="#signupModal">Sign Up!</a></li>


<!-- Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <h4 class="modal-title" id="myModalLabel">Sign Up!</h4>
      </div>
      <div class="modal-body">


<%= form_for @user, :url => users_path, :method => :post do |f| %>

<div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</div>

<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>

<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div>
  <%= f.label :street %>
  <%= f.text_field :street %>
</div>

<div>
  <%= f.label :unit_number %>
  <%= f.text_field :unit_number %>
</div>

<div>
  <%= f.label :city %>
  <%= f.text_field :city %>
</div>

<div>
  <%= f.label :state %>
  <%= f.text_field :state %>
</div>

<div>
  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>
</div>

<div>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
</div>

<div>
  <%= f.label :debit_card_number %>
  <%= f.text_field :debit_card_number %>
</div>

<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> 
</div>

<div>
  <%= f.submit "Sign Up!" %>
</div>

<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

        </li>
        <% end %>
        
      </ul>
      
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= render "shared/login" %>

app/views/shared/_signUp.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Sign Up
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <form>
        First name: <input type="text"><br>
        Last name: <input type="text"><br>
        Address: <input type="text"><br>
        Address: <input type="text"><br>
        Cellphone Number: <input type="text"><br>
        Debit Card Number: <input type="text"><br>
        <select>
          <option value="business">Business</option>
          <option value="home">Home</option>
          <option value="apartment">Apartment/Condo/Townhome</option>
        </select>
        <input type="submit" value="Submit">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render "shared/menu" %>
<h1>Sign Up!</h1>

<%= @user.errors.full_messages %>


<%= form_for @user do |f| %>

<div>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</div>

<div>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</div>

<div>
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>

<div>
	<%= f.label :street %>
	<%= f.text_field :street %>
</div>

<div>
	<%= f.label :unit_number %>
	<%= f.text_field :unit_number %>
</div>

<div>
	<%= f.label :city %>
	<%= f.text_field :city %>
</div>

<div>
	<%= f.label :state %>
	<%= f.text_field :state %>
</div>

<div>
	<%= f.label :zip_code %>
	<%= f.text_field :zip_code %>
</div>

<div>
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</div>

<div>
	<%= f.label :debit_card_number %>
	<%= f.text_field :debit_card_number %>
</div>

<div>
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>

<div>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %> 
</div>

<div>
	<%= f.submit "Sign Up!" %>
</div>

<% end %>

app/views/users/show.html.erb
<header>
	<%= render "shared/menu" %>

	<strong>Current Cashout Balance:</strong>
	<button>Ca$hout</button>
	<button>Donate</button>
	<br/>
	<select>
  		<option value="bank-acct1">xxxx-9641</option>
  		<option value="bank-acct2">xxxx-2810</option>
  		<option value="donate">Donate to this weeks charity of choice!</option>
  	</select>
</header>
	<h4>Current Address: <%= link_to current_user.street , "https://www.google.com/maps/place/#{current_user.street.tr(" ", "+")}",:target => "_blank" %> </h4>
	<h4>Currently Scheduled Pickup:</h4> 
	<% current_user.pickups.where(completed: false).each do | f | %>
		<%= f.date.strftime("[%m|%d|%Y]") %>
	<% end %>
	<div id="pickup-scheduler">
			<%= form_for @pickup do |f| %>
		<div>
			<%= f.label :date %>
			<%= f.text_field :date, id: "datepicker" %>
		</div>		

 	<script>
	  
	  $(function() {
	    $( "#datepicker" ).datepicker({minDate: 0, dateFormat: 'yy-mm-dd'});
	    	    
	  });
	   
	  </script>		



	<%= f.submit "Schedule!" %>
	<% end %>
	</div>

	<div id="confirmations">
	<strong>Previous Successful Pickups!</strong>
	<% current_user.pickups.where(completed: true).each do | f | %>
		<%= f.date.strftime("[%m|%d|%Y]") %>
	<% end %>
		
	</div>

	<div id="charities">
		<table>
		  <tr>
		    <th>This Week's Charities</th>
		  </tr>
		  <tr>
		    <td>charity 1</td>
		    <td>charity 2</td>
		    <td>charity 3</td>
		  </tr>
		</table>
	</div>

	<% if current_user.id == current_user.id %>
		 
		 <%= link_to "Delete my account that helps save the world", current_user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>
	 <% end %>

app/views/welcome/index.html.erb
<%= render "shared/menu" %>
	
		
	
	<div class="container row" class="main-block" >
		<h1>TrVshio</h1>
		<h4 id="fact"> <strong>Fact:</strong> <%= @compliment %> </h4>
		
		<br/>
		<br/>
		<br/>


	</div>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<div class="sub-blocks row">
		<div id="about" class="col-md-4">
			<strong>About</strong>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>

		<div id="benefits" class="col-md-4">
			<strong>Benefits</strong>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>

		<div id="charities" class="col-md-4">
			<strong>This week's Charities</strong>
			<span id="charity-links">
				<li>Charity 1</li>
				<li>Charity 2</li>
				<li>Charity 3</li>
			</span>
		</div>

		<ul>Proof of Donations</ul>
	</div>